name: neovimfiles

on: [push, pull_request]

jobs:
  linux-build:
    name: Testing install script in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [
          ubuntu-latest,
          ubuntu-18.04,
          ubuntu-16.04,
        ]

    env:
      GITHUB: true
      YCM: 1

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt install wget curl git
          wget -O screenfetch-dev https://git.io/vaHfR
          chmod +x screenfetch-dev
          ./screenfetch-dev

          sudo apt install -y shellcheck python3-setuptools python-setuptools build-essential cmake python3-dev
          sudo apt install -y python3-pip  python-pip
          sudo pip2 install --upgrade pip
          sudo pip3 install --upgrade pip
      - name: Fetch script
        run: |
          curl -OL https://raw.githubusercontent.com/Mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
      - name: Install dotfiles
        run: |
          ./install.sh --verbose --vim --nvim
      - name: Test neovim and stock vim
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./test/test.sh
      - name: Install new vim
        run: |
          sudo apt install vim -y
      - name: Test latest vim
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./test/test.sh --vim

  osx-build:
    name: Testing install script in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [
          macOS-latest,
        ]

    env:
      GITHUB: true

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          brew install git shellcheck neovim cmake wget
          wget -O screenfetch-dev https://git.io/vaHfR
          chmod +x screenfetch-dev
          ./screenfetch-dev
      - name: Fetch script
        run: |
          curl -OL https://raw.githubusercontent.com/Mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
      - name: Install dotfiles
        run: |
          ./install.sh --verbose --vim --nvim=dotfiles
      - name: Test neovim and stock vim
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./test/test.sh
      - name: Install new vim
        run: |
          brew install vim
      - name: Test latest vim
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./test/test.sh --vim

  windows-build:
    name: Testing install script in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [
          windows-latest,
          windows-2019,
          windows-2016
        ]

    env:
      GITHUB: true

    steps:
      - uses: actions/checkout@v1
      - name: Enable Scoop
        shell: powershell
        run: |
          iwr -useb get.scoop.sh | iex
      - name: Install dependencies
        shell: powershell
        run: |
          $env:PATH = "$env:USERPROFILE\scoop\shims;$PATH"
          $env:PATH = "$env:USERPROFILE\.local\bin;$env:PATH"
          scoop install python git curl vim neovim cmake gcc
      - name: Fetch script
        shell: bash
        run: |
          export PATH="$HOME/scoop/shims:$PATH"
          curl -OL https://raw.githubusercontent.com/Mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
      - name: Install dotfiles
        shell: bash
        run: |
          export PATH="$HOME/scoop/shims:$PATH"
          ./install.sh --verbose --vim --nvim=dotfiles
      - name: Basic stock test
        shell: bash
        run: |
          export PATH="$HOME/scoop/shims:$PATH"
          ./test/test.sh
