name: neovimfiles

on: [push, pull_request]

jobs:
  linux-build:
    name: Testing install script in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [
          ubuntu-latest,
          ubuntu-18.04,
        ]

    env:
      GITHUB: true

    steps:
      - uses: actions/checkout@v1
      - name: OS Info
        run: |
          sudo apt install wget
          wget -O screenfetch-dev https://git.io/vaHfR
          chmod +x screenfetch-dev
          ./screenfetch-dev
      - name: Install dependencies
        run: |
          sudo apt install -y curl git shellcheck python3-setuptools python-setuptools build-essential cmake python3-dev
          sudo apt install -y python3-pip  python-pip
          sudo pip2 install --upgrade pip
          sudo pip3 install --upgrade pip
      - name: Fetch script
        run: |
          curl -OL https://raw.githubusercontent.com/Mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
      - name: Install dotfiles
        run: |
          ./install.sh --verbose --vim --nvim
      - name: Test neovim and stock vim
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./test/test.sh
      - name: Test latest vim
        run: |
          sudo apt install vim -y
          export PATH="$HOME/.local/bin:$PATH"
          ./test/test.sh --vim
      - name: Test latest neovim
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./install.sh --neovim dev --force
          ./test/test.sh --nvim

  osx-build:
    name: Testing install script in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [
          macOS-latest,
        ]

    env:
      GITHUB: true

    steps:
      - uses: actions/checkout@v1
      - name: OS Info
        run: |
          brew install git shellcheck neovim cmake wget
          wget -O screenfetch-dev https://git.io/vaHfR
          chmod +x screenfetch-dev
          ./screenfetch-dev
      - name: Fetch script
        run: |
          curl -OL https://raw.githubusercontent.com/Mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
      - name: Install dotfiles
        run: |
          ./install.sh --verbose --vim --nvim=dotfiles
      - name: Test neovim and stock vim
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./test/test.sh
      - name: Install new vim
        run: |
          brew install vim
      - name: Test latest vim
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          ./test/test.sh --vim

  windows-build:
    name: Testing install script in ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [
          windows-latest,
          windows-2019,
          windows-2016
        ]

    env:
      GITHUB: true

    steps:
      - uses: actions/checkout@v1
      - name: Enable Chocolatey
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
      - name: Install dependencies
        shell: powershell
        run: |
          choco install -y python git curl vim neovim mingw cmake
      - name: Fetch script
        shell: bash
        run: |
          curl -OL https://raw.githubusercontent.com/Mike325/dotfiles/master/install.sh
          chmod +x ./install.sh
      - name: Install dotfiles
        shell: bash
        run: |
          ./install.sh --verbose --vim --nvim=dotfiles
      - name: Basic stock test
        shell: bash
        run: |
          export PATH="/c/tools/neovim/Neovim/bin:$PATH"
          ./test/test.sh
